-- GENERATED by scripts/generate-oversight-policies.mjs — reviewed before applying.
--
-- Every SELECT policy that gated visibility by naming 'admin' and
-- 'finance_approver' now asks `oversight_roles()` instead. The predicate is
-- otherwise byte-identical to what the live catalogue held, because it was read
-- from there rather than retyped.
--
-- What changes: `executive` — the MD of TFML, the Managing Partner of OEA — can
-- see what finance can see. What does not change: who may WRITE. No write policy
-- is touched here, so bank configuration, ledger posting and reconciliation stay
-- exactly where they were.

create or replace function oversight_roles()
returns user_role[] language sql immutable set search_path = public as $$
  select array['admin', 'finance_approver', 'executive']::user_role[];
$$;

create or replace function oversight_roles_with_fm()
returns user_role[] language sql immutable set search_path = public as $$
  select array['admin', 'facility_manager', 'finance_approver', 'executive']::user_role[];
$$;

comment on function oversight_roles is
  'Who may SEE the money and the audit trail. One definition instead of the same array in twenty policies — adding the next oversight role is one line here.';

drop policy if exists audit_log_select on audit_log;
create policy audit_log_select on audit_log for select
  using (((org_id = current_user_org_id()) AND ((actor_id = auth.uid()) OR (current_user_role() = ANY (oversight_roles())))));

drop policy if exists bank_accounts_select on bank_accounts;
create policy bank_accounts_select on bank_accounts for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists bank_statement_lines_select on bank_statement_lines;
create policy bank_statement_lines_select on bank_statement_lines for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists email_deliveries_select on email_deliveries;
create policy email_deliveries_select on email_deliveries for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles_with_fm()))));

drop policy if exists gateway_events_select on gateway_events;
create policy gateway_events_select on gateway_events for select
  using ((current_user_role() = ANY (oversight_roles())));

drop policy if exists ledger_accounts_select on ledger_accounts;
create policy ledger_accounts_select on ledger_accounts for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists ledger_entries_select on ledger_entries;
create policy ledger_entries_select on ledger_entries for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists ledger_postings_select on ledger_postings;
create policy ledger_postings_select on ledger_postings for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists notifications_select on notifications;
create policy notifications_select on notifications for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles_with_fm()))));

drop policy if exists payment_intents_select on payment_intents;
create policy payment_intents_select on payment_intents for select
  using (((org_id = current_user_org_id()) AND ((payer_user_id = auth.uid()) OR (current_user_role() = ANY (oversight_roles())))));

drop policy if exists payment_settings_select on payment_settings;
create policy payment_settings_select on payment_settings for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles_with_fm()))));

drop policy if exists payments_select on payments;
create policy payments_select on payments for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (vendor_id IN ( SELECT vendors.id
   FROM vendors
  WHERE (vendors.user_id = auth.uid()))) OR ((current_user_role() = 'facility_manager'::user_role) AND (vendor_id IN ( SELECT current_user_scoped_vendor_ids() AS current_user_scoped_vendor_ids))))));

drop policy if exists payout_recipients_select on payout_recipients;
create policy payout_recipients_select on payout_recipients for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (user_id = auth.uid()) OR (vendor_id IN ( SELECT vendors.id
   FROM vendors
  WHERE (vendors.user_id = auth.uid()))))));

drop policy if exists reconciliations_select on reconciliations;
create policy reconciliations_select on reconciliations for select
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (oversight_roles()))));

drop policy if exists remittances_select on remittances;
create policy remittances_select on remittances for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (recipient_id IN ( SELECT payout_recipients.id
   FROM payout_recipients
  WHERE ((payout_recipients.user_id = auth.uid()) OR (payout_recipients.vendor_id IN ( SELECT vendors.id
           FROM vendors
          WHERE (vendors.user_id = auth.uid())))))))));

drop policy if exists sc_budgets_select on sc_budgets;
create policy sc_budgets_select on sc_budgets for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (property_id IN ( SELECT current_user_property_ids() AS current_user_property_ids)))));

drop policy if exists users_select on users;
create policy users_select on users for select
  using (((org_id = current_user_org_id()) AND ((id = auth.uid()) OR (current_user_role() = ANY (oversight_roles_with_fm())))));

drop policy if exists vendor_evaluations_select on vendor_evaluations;
create policy vendor_evaluations_select on vendor_evaluations for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (vendor_id IN ( SELECT vendors.id
   FROM vendors
  WHERE (vendors.user_id = auth.uid()))) OR ((current_user_role() = 'facility_manager'::user_role) AND (vendor_id IN ( SELECT current_user_scoped_vendor_ids() AS current_user_scoped_vendor_ids))))));
