-- GENERATED by scripts/generate-fm-role-policies.mjs — reviewed before applying.
--
-- Every predicate below is byte-identical to what the live catalogue held, except
-- that `regional_manager` now sits beside `facility_manager`. Read from
-- pg_policies rather than retyped, because these include the payment policies and
-- a dropped clause there is a money bug.

create or replace function fm_roles()
returns user_role[] language sql immutable set search_path = public as $$
  -- A regional manager holds the same operational authority as a facility /
  -- properties manager, over a wider place. One definition, so the next time this
  -- set changes it changes in one file rather than eighteen policies.
  select array['facility_manager', 'regional_manager']::user_role[];
$$;

comment on function fm_roles is
  'FM/PM-or-above: the operational roles. A regional manager supersedes the facility/properties manager (board, 29 Jul 2026) — same authority, wider scope.';

drop policy if exists asset_certificates_write on asset_certificates;
create policy asset_certificates_write on asset_certificates for all
  using (((org_id = current_user_org_id()) AND ((current_user_role() = 'admin'::user_role) OR ((current_user_role() = ANY (fm_roles())) AND (asset_id IN ( SELECT assets.id
   FROM assets
  WHERE (assets.property_id IN ( SELECT current_user_property_ids() AS current_user_property_ids))))))))
  with check (((org_id = current_user_org_id()) AND ((current_user_role() = 'admin'::user_role) OR ((current_user_role() = ANY (fm_roles())) AND (asset_id IN ( SELECT assets.id
   FROM assets
  WHERE (assets.property_id IN ( SELECT current_user_property_ids() AS current_user_property_ids))))))));

drop policy if exists asset_identifiers_write on asset_identifiers;
create policy asset_identifiers_write on asset_identifiers for all
  using (((org_id = current_user_org_id()) AND ((current_user_role() = 'admin'::user_role) OR ((current_user_role() = ANY (fm_roles())) AND (asset_id IN ( SELECT assets.id
   FROM assets
  WHERE (assets.property_id IN ( SELECT current_user_property_ids() AS current_user_property_ids))))))))
  with check (((org_id = current_user_org_id()) AND ((current_user_role() = 'admin'::user_role) OR ((current_user_role() = ANY (fm_roles())) AND (asset_id IN ( SELECT assets.id
   FROM assets
  WHERE (assets.property_id IN ( SELECT current_user_property_ids() AS current_user_property_ids))))))));

drop policy if exists payment_intents_insert on payment_intents;
create policy payment_intents_insert on payment_intents for insert
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'finance_approver'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists payments_insert on payments;
create policy payments_insert on payments for insert
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists payments_select on payments;
create policy payments_select on payments for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (vendor_id IN ( SELECT vendors.id
   FROM vendors
  WHERE (vendors.user_id = auth.uid()))) OR ((current_user_role() = ANY (fm_roles())) AND (vendor_id IN ( SELECT current_user_scoped_vendor_ids() AS current_user_scoped_vendor_ids))))));

drop policy if exists payments_update on payments;
create policy payments_update on payments for update
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (ARRAY['admin'::user_role, 'finance_approver'::user_role, 'executive'::user_role])) OR ((current_user_role() = ANY (fm_roles())) AND (vendor_id IN ( SELECT current_user_scoped_vendor_ids() AS current_user_scoped_vendor_ids))))));

drop policy if exists vendor_applications_staff_select on vendor_applications;
create policy vendor_applications_staff_select on vendor_applications for select to authenticated
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists vendor_applications_staff_update on vendor_applications;
create policy vendor_applications_staff_update on vendor_applications for update to authenticated
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))))
  with check ((org_id = current_user_org_id()));

drop policy if exists vendor_evaluations_select on vendor_evaluations;
create policy vendor_evaluations_select on vendor_evaluations for select
  using (((org_id = current_user_org_id()) AND ((current_user_role() = ANY (oversight_roles())) OR (vendor_id IN ( SELECT vendors.id
   FROM vendors
  WHERE (vendors.user_id = auth.uid()))) OR ((current_user_role() = ANY (fm_roles())) AND (vendor_id IN ( SELECT current_user_scoped_vendor_ids() AS current_user_scoped_vendor_ids))))));

drop policy if exists vendor_properties_write on vendor_properties;
create policy vendor_properties_write on vendor_properties for all
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))))
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'regional_manager'::user_role]))));
