-- GENERATED by scripts/generate-fm-role-functions.mjs — reviewed before applying.
--
-- The functions and view that named `facility_manager` directly. Bodies read
-- from the catalogue and substituted, never retyped — `archive_asset` and the
-- vendor-application decisions are gates, and a clause lost in transcription is
-- exactly how the payment state machine was dropped in 0072b.

CREATE OR REPLACE FUNCTION public.approve_vendor_application(p_application_id uuid, p_notes text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  app vendor_applications%rowtype;
  v_new_vendor uuid;
begin
  select * into app from vendor_applications where id = p_application_id for update;
  if app.id is null then
    raise exception 'application not found';
  end if;
  if app.org_id is distinct from current_user_org_id() then
    raise exception 'application belongs to another organisation';
  end if;
  if current_user_role() not in ('admin', 'facility_manager', 'regional_manager') then
    raise exception 'only an administrator or FM/PM may approve vendor applications';
  end if;
  if app.status = 'approved' then
    raise exception 'this application is already approved';
  end if;
  if app.status in ('rejected', 'withdrawn') then
    raise exception 'this application was already closed';
  end if;

  insert into vendors (org_id, name, service_category, contact_email, contact_phone,
                       status, approval_status, approved_by, approved_at)
  values (app.org_id, app.business_name, app.service_category, app.contact_email,
          app.contact_phone, 'active', 'approved', auth.uid(), now())
  returning id into v_new_vendor;

  update vendor_applications
  set status = 'approved', decided_by = auth.uid(), decided_at = now(),
      decision_notes = p_notes, vendor_id = v_new_vendor
  where id = p_application_id;

  return v_new_vendor;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_vendor_application(p_application_id uuid, p_notes text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare app vendor_applications%rowtype;
begin
  select * into app from vendor_applications where id = p_application_id for update;
  if app.id is null then raise exception 'application not found'; end if;
  if app.org_id is distinct from current_user_org_id() then
    raise exception 'application belongs to another organisation';
  end if;
  if current_user_role() not in ('admin', 'facility_manager', 'regional_manager') then
    raise exception 'only an administrator or FM/PM may decide vendor applications';
  end if;
  if app.status in ('approved', 'rejected', 'withdrawn') then
    raise exception 'this application was already closed';
  end if;

  update vendor_applications
  set status = 'rejected', decided_by = auth.uid(), decided_at = now(), decision_notes = p_notes
  where id = p_application_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.archive_asset(p_asset_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org uuid;
  v_property uuid;
  v_role user_role := current_user_role();
begin
  select org_id, property_id into v_org, v_property
  from assets where id = p_asset_id and deleted_at is null;

  if v_org is null then
    raise exception 'asset not found or already archived';
  end if;

  -- Same org as the caller, always.
  if v_org is distinct from current_user_org_id() then
    raise exception 'asset belongs to another organisation';
  end if;

  -- Admin org-wide; FM/PM only on properties they are staked to.
  if not (
    v_role = 'admin'
    or (v_role = any (fm_roles())
        and v_property in (select current_user_property_ids()))
  ) then
    raise exception 'only an administrator or the managing FM/PM may archive this asset';
  end if;

  -- Fires audit_asset_write, so archiving is recorded like any other change.
  update assets set deleted_at = now() where id = p_asset_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.restore_asset(p_asset_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org uuid;
  v_property uuid;
  v_tag text;
  v_role user_role := current_user_role();
begin
  select org_id, property_id, asset_tag into v_org, v_property, v_tag
  from assets where id = p_asset_id and deleted_at is not null;

  if v_org is null then
    raise exception 'archived asset not found';
  end if;

  if v_org is distinct from current_user_org_id() then
    raise exception 'asset belongs to another organisation';
  end if;

  if not (
    v_role = 'admin'
    or (v_role = any (fm_roles())
        and v_property in (select current_user_property_ids()))
  ) then
    raise exception 'only an administrator or the managing FM/PM may restore this asset';
  end if;

  -- The unique tag index ignores archived rows, so the tag may have been reused
  -- while this asset was archived. Refuse rather than silently create a clash.
  if exists (
    select 1 from assets
    where org_id = v_org and lower(asset_tag) = lower(v_tag)
      and deleted_at is null and id <> p_asset_id
  ) then
    raise exception 'asset tag % is now in use by an active asset', v_tag;
  end if;

  update assets set deleted_at = null where id = p_asset_id;
end;
$function$
;

-- The two the generator could not match: both name the roles as a plain-quoted
-- array, which no substitution above covers.

-- Notifications, users and email deliveries are readable by "oversight plus the
-- FM/PM". A regional manager is the FM/PM for a whole region, so they belong here.
create or replace function oversight_roles_with_fm()
returns user_role[] language sql immutable set search_path = public as $$
  select array['admin', 'facility_manager', 'regional_manager',
               'finance_approver', 'executive']::user_role[];
$$;

comment on function oversight_roles_with_fm is
  'Oversight plus the operational managers. Distinct from oversight_roles(), which is money and the audit trail only.';

-- `vendor_overview` withholds vendor contact details from a viewer. Definer
-- rights, so its WHERE clause IS the boundary — a regional manager has to be
-- named in it to see the vendors working their region.
create or replace view vendor_overview as
  select
    v.id, v.org_id, v.name, v.service_category, v.status,
    v.approval_status, v.created_at
  from vendors v
  where v.org_id = current_user_org_id()
    and current_user_role() = any (
      array['viewer', 'admin', 'facility_manager', 'regional_manager',
            'finance_approver', 'executive']::user_role[]
    );

comment on view vendor_overview is
  'Vendors without contact_email/contact_phone. Definer rights, so this WHERE clause is the security boundary.';
