-- GENERATED by scripts/generate-property-manager-split.mjs — reviewed before applying.
--
-- OEA has facilities managers of its own now, so `facility_manager` can no
-- longer be one role wearing two brand labels. 0182 added the enum value; this
-- file makes every rule that names the role literally admit the new one too.
--
-- Every predicate and function body below is byte-identical to what the live
-- catalogue held, except that `property_manager` now sits beside
-- `facility_manager`. Read from pg_policies / pg_get_functiondef rather than
-- retyped — these include submit_vendor_invoice, raise_ops_requisition and
-- payment_chain_stages, and a clause lost to a typo there is a money bug.
--
-- ⚠️ Read the two hand-written definitions at the top FIRST. `fm_roles()` is
-- the single operational resolver (locked decision 8) and roughly thirty
-- policies reach the role only through it — extending it is what covers the
-- other nine-tenths of the estate that this generator never had to touch.

-- ── The resolvers, extended (decision 8: one resolver, never a second) ─────
create or replace function fm_roles()
returns user_role[] language sql immutable set search_path = public as $$
  -- A regional manager holds the same operational authority as a facility /
  -- properties manager, over a wider place. A PROPERTY manager holds it over a
  -- different discipline — OEA lets and manages tenancies where TFML maintains
  -- plant — but the operational authority itself is identical, which is why
  -- this is one more element and not a parallel set of policies.
  select array['facility_manager', 'property_manager', 'regional_manager']::user_role[];
$$;

comment on function fm_roles is
  'FM/PM-or-above: the operational roles. A regional manager supersedes the facility/properties manager (board, 29 Jul 2026) — same authority, wider scope. A property manager (board, 21 Aug 2026) is the OEA-side twin of the facility manager — same authority, different discipline — added because OEA now employs both.';

create or replace function oversight_roles_with_fm()
returns user_role[] language sql immutable set search_path = public as $$
  select array['admin', 'facility_manager', 'property_manager', 'regional_manager',
               'finance_approver', 'executive']::user_role[];
$$;

-- Seniority. The property manager is the facility manager's peer, not their
-- senior: same rank, so neither can invite the other and both sit below the
-- regional manager who supersedes them. 0078c's rule is "strictly below your
-- own rank", so equal ranks cannot mint each other — which is the intent.
create or replace function role_rank(p_role user_role)
returns integer language sql immutable as $$
  select case p_role
           when 'admin'                  then 100
           when 'executive'              then 90
           when 'finance_approver'       then 70
           when 'payment_approver'       then 65
           when 'payment_audit_approver' then 64
           when 'regional_manager'       then 60
           when 'facility_manager'       then 50
           when 'property_manager'       then 50
           when 'fm_ops_staff'           then 30
           when 'property_owner'         then 20
           when 'viewer'                 then 15
           when 'vendor'                 then 10
           when 'tenant'                 then 10
           else 0
         end;
$$;

-- ── Policies that name the role literally ─────────────────────────────────
drop policy if exists payment_intents_insert on payment_intents;
create policy payment_intents_insert on payment_intents for insert
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'finance_approver'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists payments_insert on payments;
create policy payments_insert on payments for insert
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists vendor_applications_staff_select on vendor_applications;
create policy vendor_applications_staff_select on vendor_applications for select to authenticated
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))));

drop policy if exists vendor_applications_staff_update on vendor_applications;
create policy vendor_applications_staff_update on vendor_applications for update to authenticated
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))))
  with check ((org_id = current_user_org_id()));

drop policy if exists vendor_properties_write on vendor_properties;
create policy vendor_properties_write on vendor_properties for all
  using (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))))
  with check (((org_id = current_user_org_id()) AND (current_user_role() = ANY (ARRAY['admin'::user_role, 'facility_manager'::user_role, 'property_manager'::user_role, 'regional_manager'::user_role]))));

-- ── Functions that name the role literally ────────────────────────────────
CREATE OR REPLACE FUNCTION public.approve_vendor_application(p_application_id uuid, p_notes text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  app vendor_applications%rowtype;
  v_new_vendor uuid;
begin
  select * into app from vendor_applications where id = p_application_id for update;
  if app.id is null then
    raise exception 'application not found';
  end if;
  if app.org_id is distinct from current_user_org_id() then
    raise exception 'application belongs to another organisation';
  end if;
  if current_user_role() not in ('admin', 'facility_manager', 'property_manager', 'regional_manager') then
    raise exception 'only an administrator or FM/PM may approve vendor applications';
  end if;
  if app.status = 'approved' then
    raise exception 'this application is already approved';
  end if;
  if app.status in ('rejected', 'withdrawn') then
    raise exception 'this application was already closed';
  end if;

  insert into vendors (org_id, name, service_category, contact_email, contact_phone,
                       status, approval_status, approved_by, approved_at)
  values (app.org_id, app.business_name, app.service_category, app.contact_email,
          app.contact_phone, 'active', 'approved', auth.uid(), now())
  returning id into v_new_vendor;

  update vendor_applications
  set status = 'approved', decided_by = auth.uid(), decided_at = now(),
      decision_notes = p_notes, vendor_id = v_new_vendor
  where id = p_application_id;

  return v_new_vendor;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.complete_work_order(p_ticket_id uuid, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t tickets%rowtype;
begin
  select * into t from tickets where id = p_ticket_id;
  if t.id is null then raise exception 'that request could not be found'; end if;

  if t.assigned_vendor_id is null
     or t.assigned_vendor_id not in (select current_user_vendor_ids()) then
    raise exception 'only the vendor this job is assigned to can mark it complete';
  end if;
  if not vendor_user_can('manage_work') then
    raise exception 'your account is not set up to report work complete for this company';
  end if;

  if t.status in ('resolved', 'closed') then
    raise exception 'that job is already marked complete';
  end if;

  update tickets set status = 'resolved' where id = p_ticket_id;

  if length(trim(coalesce(p_note, ''))) > 0 then
    insert into ticket_messages (org_id, ticket_id, author, body)
    values (t.org_id, p_ticket_id, 'system',
            'Marked complete by the contractor: ' || trim(p_note));
  end if;

  perform notify_role(
    t.org_id,
    array['admin', 'facility_manager', 'property_manager', 'regional_manager']::user_role[],
    'request',
    'A contractor marked a job complete',
    coalesce(nullif(trim(p_note), ''), 'Ready for your verification.'),
    '/dashboard/tickets/' || p_ticket_id::text
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.decline_work_order(p_ticket_id uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t tickets%rowtype;
begin
  select * into t from tickets where id = p_ticket_id;
  if t.id is null then raise exception 'that request could not be found'; end if;

  if t.assigned_vendor_id is null
     or t.assigned_vendor_id not in (select current_user_vendor_ids()) then
    raise exception 'only the vendor this job is assigned to can decline it';
  end if;
  if not vendor_user_can('manage_work') then
    raise exception 'your account is not set up to accept or decline jobs for this company';
  end if;

  if t.status in ('resolved', 'closed') then
    raise exception 'that job is already finished';
  end if;

  if length(trim(coalesce(p_reason, ''))) < 10 then
    raise exception 'give a reason of at least 10 characters so the team can re-assign it properly';
  end if;

  update tickets
     set assigned_vendor_id = null,
         assigned_to_user_id = null,
         assigned_at = null,
         acknowledged_at = null,
         status = 'open'
   where id = p_ticket_id;

  insert into ticket_messages (org_id, ticket_id, author, body)
  values (t.org_id, p_ticket_id,
          'system',
          'Declined by the assigned contractor: ' || trim(p_reason));

  perform notify_role(
    t.org_id,
    array['admin', 'facility_manager', 'property_manager', 'regional_manager']::user_role[],
    'assignment',
    'A contractor declined a job',
    trim(p_reason),
    '/dashboard/tickets/' || p_ticket_id::text
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.offer_vendor_introduction(p_target_org_slug text, p_consent_statement text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_vendor vendors%rowtype;
  r vendor_registrations%rowtype;
  v_target uuid;
  v_id uuid;
begin
  select * into v_vendor from vendors where id = current_user_vendor_id();
  if v_vendor.id is null then
    raise exception 'only a vendor can offer their own registration';
  end if;
  if not vendor_user_can('manage_profile') then
    raise exception 'your account is not set up to share this company''s registration';
  end if;

  select * into r from vendor_registrations where vendor_id = v_vendor.id;
  if r.id is null or r.status <> 'approved' then
    raise exception 'your registration must be approved here before it can be carried anywhere else';
  end if;

  if length(trim(coalesce(p_consent_statement, ''))) < 20 then
    raise exception 'the consent wording shown to you must be recorded with the offer';
  end if;

  select o.id into v_target
    from orgs o
   where lower(o.slug) = lower(trim(coalesce(p_target_org_slug, '')))
     and o.deleted_at is null
   limit 1;

  -- One message for unknown, retired, and "that is where you already are".
  -- Three different refusals would be three different facts about the platform.
  if v_target is null or v_target = v_vendor.org_id then
    raise exception 'that organisation could not be found';
  end if;

  if exists (
    select 1 from vendor_introductions
     where source_vendor_id = v_vendor.id and target_org_id = v_target and status = 'offered'
  ) then
    raise exception 'you have already offered your registration there and it is still waiting';
  end if;

  insert into vendor_introductions (
    source_org_id, source_vendor_id, offered_by, target_org_id,
    consent_statement
  ) values (
    v_vendor.org_id, v_vendor.id, auth.uid(), v_target,
    trim(p_consent_statement)
  )
  returning id into v_id;

  perform notify_role(
    v_target,
    array['admin', 'facility_manager', 'property_manager', 'regional_manager']::user_role[],
    'application',
    'A contractor offered their registration',
    v_vendor.name || ' has an approved registration elsewhere on the platform and has consented to share it with you.',
    '/dashboard/vendors/introductions'
  );

  return v_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.payment_chain_stages()
 RETURNS TABLE(stage_order smallint, required_roles user_role[], tier_resolved boolean, label text)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select * from (values
    (1::smallint, array['facility_manager', 'property_manager','regional_manager']::user_role[], false,
     'Job sign-off and approval for payment'),
    (2::smallint, array['payment_audit_approver']::user_role[],              false,
     'Audit verification'),
    (3::smallint, array['payment_approver','executive','admin']::user_role[], true,
     'Final approval')
  ) as t(stage_order, required_roles, tier_resolved, label);
$function$
;

CREATE OR REPLACE FUNCTION public.raise_ops_requisition(p_reference text, p_lines jsonb, p_ticket_id uuid DEFAULT NULL::uuid, p_attachment_path text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_uid uuid := auth.uid();
  v_role user_role;
  v_org  uuid;
  v_req_id uuid;
  v_path text := nullif(trim(coalesce(p_attachment_path, '')), '');
  v_line jsonb;
  v_order smallint := 0;
  v_desc text;
  v_amount numeric;
  v_vendor uuid;
  v_count int;
begin
  if v_uid is null then
    raise exception 'your session expired — sign in again';
  end if;

  select role, org_id into v_role, v_org from users where id = v_uid;

  -- Raised by the people who do the work and by dispatch authority above
  -- them — the same set 0078a's fm_roles() names, plus the ops staff member
  -- themselves and an administrator.
  if v_role not in ('fm_ops_staff', 'facility_manager', 'property_manager', 'regional_manager', 'admin') then
    raise exception 'only operational staff may raise a requisition';
  end if;

  if length(trim(coalesce(p_reference, ''))) < 3 then
    raise exception 'give the requisition a reference of your own so you can reconcile it';
  end if;

  if jsonb_typeof(p_lines) is distinct from 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'a requisition needs at least one cost line';
  end if;
  if jsonb_array_length(p_lines) > 50 then
    raise exception 'a single requisition may hold at most 50 lines — split this into more than one';
  end if;

  if p_ticket_id is not null then
    if not exists (select 1 from tickets where id = p_ticket_id and org_id = v_org) then
      raise exception 'that job could not be found in your organisation';
    end if;
  end if;

  if v_path is not null and v_path !~ ('^' || v_org::text || '/') then
    raise exception 'that attachment does not belong to your organisation';
  end if;

  insert into ops_requisitions (org_id, ticket_id, raised_by, reference, invoice_attachment_path)
  values (v_org, p_ticket_id, v_uid, trim(p_reference), v_path)
  returning id into v_req_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_order := v_order + 1;
    v_desc := trim(coalesce(v_line->>'description', ''));
    v_amount := nullif(v_line->>'amount', '')::numeric;
    v_vendor := nullif(v_line->>'vendorId', '')::uuid;

    if length(v_desc) < 3 then
      raise exception 'line %: describe the cost in at least 3 characters', v_order;
    end if;
    if v_amount is null or v_amount <= 0 then
      raise exception 'line %: enter a positive amount', v_order;
    end if;
    if v_vendor is not null and not exists (
      select 1 from vendors where id = v_vendor and org_id = v_org
    ) then
      raise exception 'line %: that vendor is not registered in your organisation', v_order;
    end if;

    insert into ops_requisition_lines (requisition_id, org_id, line_order, description, amount, vendor_id)
    values (v_req_id, v_org, v_order, v_desc, v_amount, v_vendor);
  end loop;

  -- Notified the same way a vendor invoice tells finance -- the chain's stage
  -- 1 is a facility/regional manager, and they are who is actually next.
  perform notify_role(
    v_org,
    array['facility_manager', 'property_manager', 'regional_manager']::user_role[],
    'payment',
    'A requisition was raised',
    trim(p_reference) || ' awaits your sign-off',
    '/dashboard/approvals'
  );

  return v_req_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_vendor_application(p_application_id uuid, p_notes text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare app vendor_applications%rowtype;
begin
  select * into app from vendor_applications where id = p_application_id for update;
  if app.id is null then raise exception 'application not found'; end if;
  if app.org_id is distinct from current_user_org_id() then
    raise exception 'application belongs to another organisation';
  end if;
  if current_user_role() not in ('admin', 'facility_manager', 'property_manager', 'regional_manager') then
    raise exception 'only an administrator or FM/PM may decide vendor applications';
  end if;
  if app.status in ('approved', 'rejected', 'withdrawn') then
    raise exception 'this application was already closed';
  end if;

  update vendor_applications
  set status = 'rejected', decided_by = auth.uid(), decided_at = now(), decision_notes = p_notes
  where id = p_application_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.save_requisition_line_payee(p_line_id uuid, p_display_name text, p_account_name text, p_account_number_last4 text, p_recipient_code text, p_gateway text DEFAULT 'paystack'::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_uid uuid := auth.uid();
  v_role user_role;
  v_org  uuid;
  v_line ops_requisition_lines%rowtype;
  v_req  ops_requisitions%rowtype;
  v_recipient_id uuid;
begin
  if v_uid is null then
    raise exception 'your session expired — sign in again';
  end if;
  select role, org_id into v_role, v_org from users where id = v_uid;
  if v_role not in ('fm_ops_staff', 'facility_manager', 'property_manager', 'regional_manager', 'admin') then
    raise exception 'only operational staff may set who a requisition line pays';
  end if;

  select * into v_line from ops_requisition_lines where id = p_line_id;
  if v_line.id is null or v_line.org_id <> v_org then
    raise exception 'that requisition line could not be found';
  end if;
  if v_line.vendor_id is not null then
    raise exception 'this line already names a registered vendor — a line pays one place, not two';
  end if;

  select * into v_req from ops_requisitions where id = v_line.requisition_id;
  -- Locked once the chain has started: a payee changed after an approver has
  -- already acted, trusting the original one, is the integrity gap this
  -- refuses. The amount has the same protection at disbursement (0151); the
  -- payee gets it here, at the point it can still be changed safely.
  if v_req.status <> 'pending_approval' or exists (
    select 1 from payment_approvals
     where payable_type = 'ops_requisition' and payable_id = v_req.id
  ) then
    raise exception 'this requisition has already begun approval — the payee on a line cannot change now';
  end if;

  if p_recipient_code is null or length(trim(p_recipient_code)) = 0 then
    raise exception 'the bank did not return a usable recipient — nothing has been saved';
  end if;

  insert into payout_recipients (
    org_id, party, display_name, account_name, account_number_last4,
    gateway, recipient_code, currency, verified_at, created_by
  ) values (
    v_org, 'other', trim(p_display_name), trim(p_account_name), p_account_number_last4,
    -- ⚠️ `gateway` is a typed enum (`payment_gateway`), not text — an
    -- unqualified text literal fails with "column is of type payment_gateway
    -- but expression is of type text". Caught by the requisition smoke test,
    -- not by review.
    p_gateway::payment_gateway, trim(p_recipient_code), 'NGN', now(), v_uid
  )
  returning id into v_recipient_id;

  update ops_requisition_lines
     set payee_recipient_id = v_recipient_id
   where id = p_line_id;

  return v_recipient_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_vendor_invoice(p_amount numeric, p_invoice_reference text, p_ticket_id uuid DEFAULT NULL::uuid, p_attachment_path text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_vendor vendors%rowtype;
  t tickets%rowtype;
  v_id uuid;
  v_path text := nullif(trim(coalesce(p_attachment_path, '')), '');
begin
  select * into v_vendor from vendors where id = current_user_vendor_id();
  if v_vendor.id is null then
    raise exception 'only a vendor can submit an invoice';
  end if;
  if not vendor_user_can('manage_work') then
    raise exception 'your account is not set up to submit invoices for this company';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'an invoice must be for a positive amount';
  end if;
  if length(trim(coalesce(p_invoice_reference, ''))) < 3 then
    raise exception 'give the invoice a reference of your own so you can reconcile it';
  end if;

  if p_ticket_id is not null then
    select * into t from tickets where id = p_ticket_id;
    if t.id is null or t.assigned_vendor_id is distinct from v_vendor.id then
      raise exception 'that job is not yours to invoice';
    end if;
    if t.status not in ('resolved', 'closed') then
      raise exception 'finish the job before invoicing for it';
    end if;
  end if;

  if p_ticket_id is not null and exists (
    select 1 from payments
     where ticket_id = p_ticket_id and status <> 'rejected'
  ) then
    raise exception 'an invoice for that job has already been submitted';
  end if;

  if v_path is not null and v_path !~ ('^' || v_vendor.org_id::text || '/') then
    raise exception 'that attachment does not belong to your organisation';
  end if;

  insert into payments (
    org_id, vendor_id, ticket_id, invoice_reference, amount, status, invoice_attachment_path
  ) values (
    v_vendor.org_id, v_vendor.id, p_ticket_id,
    trim(p_invoice_reference), p_amount, 'pending_verification', v_path
  )
  returning id into v_id;

  perform notify_role(
    v_vendor.org_id,
    array['admin', 'facility_manager', 'property_manager', 'finance_approver']::user_role[],
    'payment',
    'A contractor submitted an invoice',
    v_vendor.name || ' submitted ' || trim(p_invoice_reference),
    '/dashboard/payments/' || v_id::text
  );

  return v_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_vendor_registration()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_vendor_id uuid := current_user_vendor_id();
  r vendor_registrations%rowtype;
  v_missing text[];
  v_name text;
  v_org uuid;
begin
  if v_vendor_id is null then
    raise exception 'only a vendor can submit their own registration';
  end if;
  if not vendor_user_can('manage_profile') then
    raise exception 'your account is not set up to submit this company''s registration';
  end if;

  select * into r from vendor_registrations where vendor_id = v_vendor_id for update;
  if r.id is null then
    raise exception 'there is nothing to submit yet';
  end if;
  if r.status = 'submitted' then
    raise exception 'this registration is already with the team for review';
  end if;
  if r.status = 'approved' then
    raise exception 'this registration has already been approved';
  end if;

  select array(select vendor_registration_missing(v_vendor_id)) into v_missing;
  if cardinality(v_missing) > 0 then
    raise exception 'still outstanding: %', array_to_string(v_missing, ', ');
  end if;

  update vendor_registrations
     set status = 'submitted', submitted_at = now(), submitted_by = auth.uid(),
         updated_at = now()
   where id = r.id;

  select name, org_id into v_name, v_org from vendors where id = v_vendor_id;

  perform notify_role(
    v_org,
    array['admin', 'facility_manager', 'property_manager', 'regional_manager']::user_role[],
    -- 'application' is the notification kind for "a vendor thing to review"
    -- (0025's allowed list); there is no 'vendor' kind and adding one would
    -- widen a CHECK that every existing consumer already switches on.
    'application',
    'A contractor submitted their registration',
    v_name || ' has completed their registration pack and it is ready to review.',
    '/dashboard/vendors/' || v_vendor_id::text
  );
end;
$function$
;

-- ── The B7 baseline learns the role ────────────────────────────────────────
--
-- By hand rather than generated: this needs a new role ARM, not a wider list.
-- The property manager's grants are the facility manager's grants — same
-- operational authority, different discipline — so the arm is shared rather
-- than copied, which is what keeps the two from drifting the next time B7
-- moves.
create or replace function seed_b7_permissions(p_org_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  cap record;
  r user_role;
  v_granted boolean;
begin
  for cap in select key from capabilities where not locked loop
    foreach r in array array['tenant','vendor','fm_ops_staff','facility_manager',
                             'property_manager',
                             'finance_approver','property_owner','admin','viewer',
                             'executive','regional_manager',
                             'payment_audit_approver','payment_approver']::user_role[]
    loop
      v_granted := case
        when cap.key = 'tickets.assign_without_review' then false

        when r = 'admin' then true

        when r = 'executive' then cap.key in (
          'tickets.read_all', 'assets.read', 'sc.read_all', 'properties.read_all',
          'vendors.read', 'bi.read', 'tickets.triage_unassigned'
        )

        when r in ('payment_audit_approver', 'payment_approver') then cap.key in (
          'vendors.read', 'bi.read', 'properties.read_all'
        )

        when r = 'regional_manager' then cap.key in (
          'tickets.assign', 'tickets.close', 'tickets.triage_unassigned',
          'assets.write', 'assets.import',
          'vendors.read', 'vendors.write', 'vendors.evaluate',
          'properties.write', 'units.assign_occupant',
          'people.invite', 'bi.read',
          'applications.review_all'
        )

        when cap.key in ('tickets.read_all', 'assets.read',
                         'sc.read_all', 'properties.read_all')
          then r = 'finance_approver'

        -- ⚠️ `property_manager` joins `facility_manager` in every arm below,
        -- deliberately as an equal rather than a copied block. Two lists that
        -- must agree will eventually disagree (lib/roles.ts, on why
        -- INVITABLE_ROLES was collapsed to one array) — and these are the
        -- operational write capabilities, so disagreement here means one of the
        -- two managers silently cannot do their job.
        when cap.key in ('tickets.assign', 'tickets.close',
                         'assets.write', 'assets.import',
                         'vendors.write', 'vendors.evaluate',
                         'properties.write', 'units.assign_occupant',
                         'people.invite')
          then r in ('facility_manager', 'property_manager')

        when cap.key = 'vendors.read'
          then r in ('facility_manager', 'property_manager', 'finance_approver')
        when cap.key = 'sc.manage'    then r = 'finance_approver'
        when cap.key = 'bi.read'
          then r in ('facility_manager', 'property_manager',
                     'finance_approver', 'property_owner')
        when cap.key = 'people.deactivate' then false
        when cap.key = 'tickets.triage_unassigned' then false

        else false
      end;

      insert into role_permissions (org_id, role, capability, granted)
      values (p_org_id, r, cap.key, v_granted)
      on conflict (org_id, role, capability) do nothing;
    end loop;
  end loop;
end;
$$;

-- ── Existing orgs get the role's rows ──────────────────────────────────────
--
-- `seed_b7_permissions` only ever reaches an org at creation or reset time, so
-- every org that already exists would otherwise hold no `property_manager` row
-- at all — and `has_permission` reads a missing row as no grant, which would
-- make the new role real but powerless.
--
-- 📌 Copied from what `facility_manager` ACTUALLY HOLDS IN THIS ORG, not from
-- the B7 default. An operator may have deliberately opened or closed a
-- capability for the FM here (decision 7 exists precisely so they can), and
-- seeding the twin from the pristine baseline would silently undo that
-- judgement for one of the two peers. The new role starts exactly where the
-- role it was split from stands.
insert into role_permissions (org_id, role, capability, granted)
select rp.org_id, 'property_manager'::user_role, rp.capability, rp.granted
  from role_permissions rp
 where rp.role = 'facility_manager'
on conflict (org_id, role, capability) do nothing;

-- ── OEA's existing managers become property managers ───────────────────────
--
-- Everyone holding `facility_manager` in an OEA org was doing the PROPERTY
-- manager's job — that is what the role rendered as on their screen and what
-- they were hired to do. Leaving them on `facility_manager` would silently
-- re-label them overnight, on a portal where the label is the job title.
--
-- TFML's are untouched: there the role already meant facilities management and
-- still does. Nobody's effective access changes either way — the two roles hold
-- identical grants on the day of the split, by construction above.
--
-- ⚠️ Pending INVITATIONS are deliberately left alone. An unaccepted invite to
-- `facility_manager` in an OEA org is now a meaningful thing to have sent, not
-- a mistake to correct — that is the whole point of the split — and invites
-- expire in 14 days regardless.
-- The audit row is written from the UPDATE's own RETURNING, so it records the
-- rows this migration actually moved rather than every OEA property manager
-- who happens to exist when it runs — including any created later by an
-- administrator, who were never migrated and must not appear to have been.
with moved as (
  update users u
     set role = 'property_manager'
    from orgs o
   where o.id = u.org_id
     and o.delivery_brand = 'OEA'
     and u.role = 'facility_manager'
  returning u.id, u.org_id
)
insert into audit_log (org_id, actor_id, action, entity_type, entity_id,
                       before_state, after_state)
select m.org_id, null, 'role.split_migration', 'user', m.id,
       jsonb_build_object('role', 'facility_manager'),
       jsonb_build_object('role', 'property_manager',
                          'reason', 'FM/PM split, board 21 Aug 2026 — OEA now employs both')
  from moved m;
