-- A null role walks straight past a negative guard.
--
-- 0194 made `current_user_role()` return NULL for a deactivated account. That is
-- the right answer, and it silently changed the contract of a function that
-- seventeen plpgsql guards were written against — nearly every one of them in the
-- shape
--
--     if current_user_role() not in ('admin', 'finance_approver') then raise ...
--
-- which is FAIL-OPEN under NULL. `null not in (...)` is NULL, the IF never fires,
-- and the guard is skipped by exactly the caller it exists to stop.
--
-- Sixteen of the seventeen are saved by an `is distinct from current_user_org_id()`
-- check standing ahead of them, which does raise on NULL. That is ordering, not
-- design; it held only for as long as every author happened to write the org check
-- first.
--
-- `submit_vendor_evaluation` (0104) is the one that did not. Its fm_pm branch reads
--
--     if not (current_user_role() = any (oversight_roles())
--             or (current_user_role() = any (fm_roles()) and ...)) then raise
--
-- — NULL throughout for a deactivated caller, so a deactivated FM/PM could still
-- submit a vendor evaluation. Not a cosmetic write: the evaluation feeds the KPI
-- score, and B4 puts the performance gate in front of every vendor payment. The
-- tenant branch beside it compares `auth.uid()` directly and was never at risk,
-- which is why this survived a reading of the same function.
--
-- The guard below is positive rather than negative — `not current_user_is_active()`
-- where is_active() is `exists(...)` and therefore never NULL — so it cannot
-- acquire the same defect.
--
-- 📌 Found by `verify-deactivation.mjs` section E, not by review. That section now
-- lints the catalogue for the shape, so the eighteenth guard written this way
-- fails a check rather than waiting for someone to notice it.
--
-- A follow-up to 0195, which established the rule: everything in `public`
-- reaching auth.uid() must resolve identity through a deactivation-aware path,
-- or be a declared exception. See 0195's header for what that was written
-- about and why the bodies below are generated rather than typed.
--
-- ⚠️ Generated by scripts/generate-deactivation-guards.mjs from
-- `pg_get_functiondef`. Regenerate rather than hand-editing.

-- ── The bodies, rewritten from the catalogue ──────────────────────────────
-- submit_vendor_evaluation: guard injected after the opening begin.
CREATE OR REPLACE FUNCTION public.submit_vendor_evaluation(p_ticket_id uuid, p_source text, p_responses jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t tickets%rowtype;
  v_org uuid;
  v_vendor uuid;
  v_eval uuid;
  v_dims eval_dimension[];
  v_line jsonb;
  crit evaluation_criteria%rowtype;
  v_points numeric;
  v_quality numeric; v_compliance numeric; v_satisfaction numeric;
  v_response numeric; v_completion numeric;
  v_seen_criteria uuid[] := '{}';
begin
  -- Deactivation guard. Null-safe by construction: current_user_is_active()
  -- returns a boolean from exists(), never NULL, and the auth.uid() test keeps
  -- the service role (scheduled jobs, webhooks) passing straight through.
  if auth.uid() is not null and not current_user_is_active() then
    raise exception 'this account has been deactivated';
  end if;

  if p_source not in ('tenant', 'fm_pm') then
    raise exception 'unknown evaluation source: %', p_source;
  end if;

  select * into t from tickets where id = p_ticket_id;
  if t.id is null then raise exception 'that request could not be found'; end if;
  v_org := t.org_id;
  v_vendor := t.assigned_vendor_id;

  if v_vendor is null then
    raise exception 'this request has no vendor assigned — nothing to evaluate';
  end if;
  if t.status not in ('resolved', 'closed') then
    raise exception 'this request has not been completed yet';
  end if;

  -- Standing to evaluate. Checked here, not left to RLS, because the two
  -- sources have entirely different authority rules and bundling them with the
  -- scoring keeps "who may say what" and "what did they say" from drifting
  -- apart the way two independently-maintained checks eventually do.
  if auth.uid() is not null then
    if p_source = 'tenant' then
      if t.sender_id is distinct from auth.uid() then
        raise exception 'only the person who raised this request may rate it';
      end if;
    else
      if not (
        current_user_role() = any (oversight_roles())
        or (current_user_role() = any (fm_roles())
            and v_vendor in (select current_user_scoped_vendor_ids()))
      ) then
        raise exception 'you do not have permission to evaluate this vendor';
      end if;
    end if;
  end if;

  if exists (
    select 1 from vendor_evaluations
     where ticket_id = p_ticket_id and source = p_source
  ) then
    raise exception 'this % evaluation has already been submitted for this request', p_source;
  end if;

  v_dims := case p_source
    when 'tenant' then array['satisfaction']::eval_dimension[]
    else array['quality', 'compliance']::eval_dimension[]
  end;

  -- Refuse rather than silently score zero. An org with no rubric configured
  -- for this source has no meaningful answer to "how did they do" — a 0/100
  -- would look exactly like a genuinely bad review, not like a missing setup
  -- step.
  if not exists (
    select 1 from evaluation_criteria
     where org_id = v_org and active and dimension = any (v_dims) and measure = 'manual'
  ) then
    raise exception 'the evaluation rubric has not been set up for this organisation yet';
  end if;

  insert into vendor_evaluations (org_id, vendor_id, ticket_id, source, evaluated_by)
  values (v_org, v_vendor, p_ticket_id, p_source, auth.uid())
  returning id into v_eval;

  -- ── Manual dimensions: one response per active criterion, points from the
  --    fixed value→fraction mapping for its response_type. ─────────────────
  for crit in
    select * from evaluation_criteria
     where org_id = v_org and active and dimension = any (v_dims) and measure = 'manual'
     order by sort_order
  loop
    v_line := null;
    select value_obj into v_line from (
      select jsonb_array_elements(p_responses) as value_obj
    ) x
    where (value_obj->>'criterionId')::uuid = crit.id
    limit 1;

    if v_line is null then
      raise exception 'missing a response for: %', crit.label;
    end if;

    v_points := crit.max_points * case
      when crit.response_type = 'met_partial_not_met' then
        case v_line->>'value'
          when 'met' then 1.0 when 'partial' then 0.5 when 'not_met' then 0.0
          else null end
      when crit.response_type = 'yes_no' then
        case v_line->>'value' when 'yes' then 1.0 when 'no' then 0.0 else null end
      when crit.response_type = 'scale_1_5' then
        case v_line->>'value'
          when '1' then 0.0 when '2' then 0.25 when '3' then 0.5
          when '4' then 0.75 when '5' then 1.0 else null end
    end;

    if v_points is null then
      raise exception 'not a valid response for "%": %', crit.label, v_line->>'value';
    end if;

    insert into evaluation_responses (org_id, evaluation_id, criterion_id, response_value, points_awarded)
    values (v_org, v_eval, crit.id, v_line->>'value', v_points);

    v_seen_criteria := array_append(v_seen_criteria, crit.id);
  end loop;

  -- Dimension score = the sum of points actually awarded. The seed rubric
  -- makes each manual dimension's max_points sum to 100 by construction, so no
  -- further scaling is needed — an admin who edits the rubric to sum to
  -- something else is choosing a scale, and the score is that scale.
  if p_source = 'tenant' then
    select coalesce(sum(er.points_awarded), 0) into v_satisfaction
      from evaluation_responses er where er.evaluation_id = v_eval;
    update vendor_evaluations set satisfaction_score = v_satisfaction where id = v_eval;
  else
    select coalesce(sum(er.points_awarded) filter (where ec.dimension = 'quality'), 0),
           coalesce(sum(er.points_awarded) filter (where ec.dimension = 'compliance'), 0)
      into v_quality, v_compliance
      from evaluation_responses er join evaluation_criteria ec on ec.id = er.criterion_id
     where er.evaluation_id = v_eval;

    -- ── Auto dimensions: computed from the ticket's own timestamps, against
    --    the SLA target that was ACTIVE when the ticket resolved — a
    --    criterion superseded since then must not reach back and change a
    --    score already given. Linear taper: on-target = 100, double the
    --    target or worse = 0.
    --
    -- ⚠️ Falls back to the EARLIEST version of the criterion when none was yet
    -- active at resolution time, rather than leaving the dimension null
    -- forever. Without this, every ticket resolved in the gap between "Day 11
    -- shipped" and "an admin got around to setting up the rubric" — which is
    -- not a hypothetical, it is exactly what a fresh org does on day one —
    -- could NEVER be auto-scored, because no criterion would ever satisfy
    -- `effective_from <= resolved_at`. The rubric that eventually gets set up
    -- is the best available answer to "what was the target", even for a job
    -- that finished slightly before it existed on paper.
    select * into crit from evaluation_criteria
     where org_id = v_org and dimension = 'response' and effective_from <= coalesce(t.resolved_at, now())
     order by effective_from desc limit 1;
    if crit.id is null then
      select * into crit from evaluation_criteria
       where org_id = v_org and dimension = 'response'
       order by effective_from asc limit 1;
    end if;
    if crit.id is not null and t.first_response_at is not null then
      v_response := greatest(0, least(100,
        100 * (2 - extract(epoch from (t.first_response_at - t.created_at)) / 3600.0 / crit.sla_target_hours)
      ));
    end if;

    select * into crit from evaluation_criteria
     where org_id = v_org and dimension = 'completion' and effective_from <= coalesce(t.resolved_at, now())
     order by effective_from desc limit 1;
    if crit.id is null then
      select * into crit from evaluation_criteria
       where org_id = v_org and dimension = 'completion'
       order by effective_from asc limit 1;
    end if;
    if crit.id is not null and t.resolved_at is not null then
      v_completion := greatest(0, least(100,
        100 * (2 - extract(epoch from (t.resolved_at - t.created_at)) / 3600.0 / crit.sla_target_hours)
      ));
    end if;

    update vendor_evaluations
       set quality_score = v_quality, compliance_score = v_compliance,
           response_score = v_response, completion_score = v_completion
     where id = v_eval;
  end if;

  return v_eval;
end;
$function$
;

comment on function resolve_chat_sender is
  'Who is writing to us on WhatsApp or Telegram, by their phone number. A deactivated account resolves to nobody (0195) - this path runs service-role from the webhook, so RLS and the 0194 resolvers never see it, and without the clause here the primary intake channel stayed open to someone the organisation had removed.';

-- ── The notification feed ─────────────────────────────────────────────────
-- `user_notifications_select` was `using (user_id = auth.uid())`: no org gate
-- and no deactivation. It is also what `my_notifications` reads through — that
-- one being the single non-DEFINER function in the set — so the policy fixes
-- both.
drop policy if exists user_notifications_select on user_notifications;
create policy user_notifications_select on user_notifications for select
  using (user_id = active_uid());

comment on policy user_notifications_select on user_notifications is
  'Your own notifications, for as long as the account is live (0195).';

-- ── Prove the RULE, not the list ──────────────────────────────────────────
-- 0194's check named four functions and asserted a substring appeared in each.
-- It would have passed unchanged on the day every gap above was open, which is
-- exactly what its own header argues against: it proved the clause was PRESENT,
-- never that anything REFUSED.
--
-- This asks the catalogue instead. Every function in `public` that reaches
-- auth.uid() must either resolve identity through a deactivation-aware path, or
-- be named below with the reason it cannot. A function added later that does
-- neither fails the migration that introduces it.
do $$
declare
  v_bad text[] := '{}';
  r record;
begin
  for r in
    select p.proname, pg_get_functiondef(p.oid) as def,
           pg_get_function_result(p.oid) as ret
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f'
       and pg_get_functiondef(p.oid) like '%auth.uid()%'
  loop
    -- A trigger cannot refuse a caller it was not called about: it fires on a
    -- row, and the write that reached it has already passed RLS. Guarding
    -- log_audit() would block the write it exists to record.
    continue when r.ret = 'trigger';

    continue when r.proname = any (array[
      -- creates the users row - a guard reading that row would refuse every new joiner
      'accept_invitation',
      -- not SECURITY DEFINER - runs under RLS as the caller, which already fails closed
      'reject_payment'
    ]);

    if r.def !~ '(deactivated_at\s+is\s+null|active_uid\(\)|current_user_is_active\(\)|current_user_org_id\(\)|current_user_role\(\)|current_user_property_ids\(\)|current_user_vendor_ids\(\))'
    then
      v_bad := v_bad || r.proname;
    end if;
  end loop;

  if array_length(v_bad, 1) > 0 then
    raise exception
      'These functions reach auth.uid() with no deactivation-aware path and are not declared exceptions: %',
      array_to_string(v_bad, ', ');
  end if;
end;
$$;
