-- A removed operator can still change an organisation's money controls
-- (7 Sept 2026).
--
-- Four functions, found by `verify-deactivation` section E asking the live
-- catalogue rather than by anyone reading a diff:
--
--   operator_set_approval_chain   (0248)  the chain SHAPE, per organisation
--   operator_set_approval_tiers   (0261)  whether the tier bands apply at all
--   accept_tenancy_offer          (0263)
--   my_notifications              (0221)  regressed — see below
--
-- ⚠️ The two `operator_set_*` are the ones that matter. `caller_is_operator_admin()`
-- asks for a role and an org and never asks whether the account is still live, so
-- an operator administrator who has been removed kept the ability to change
-- another organisation's approval ladder — a money control, and one decision 7
-- lists among those that "stay hardwired and never appear as toggles" precisely
-- because they are what an auditor checks. 0195's own subject was self-scoped
-- READS by a removed tenant; this is a write, one level up.
--
-- `accept_tenancy_offer` is a no-op on its ordinary path and is guarded anyway:
-- the person accepting has no account yet, so auth.uid() is null and the guard
-- passes straight through. "This one cannot be reached by a signed-in caller" is
-- an argument about today's callers, and the rule is about the class.
--
-- 📌 `my_notifications` was ALREADY fixed, by 0195, and came back. 0221 replaced
-- it to add the `target_live` column and was written from the pre-0195 body, so
-- the `active_uid()` substitution was silently undone — the same shape 0210
-- recorded when a `create or replace` reopened a revoke 0114 had closed. A replace
-- re-states the whole function, and whatever a previous migration put there that
-- the author did not know about is gone. Prose cannot prevent that; the generator
-- being re-runnable and the suite asking the catalogue is what caught it.
--
-- A follow-up to 0195, which established the rule: everything in `public`
-- reaching auth.uid() must resolve identity through a deactivation-aware path,
-- or be a declared exception. See 0195's header for what that was written
-- about and why the bodies below are generated rather than typed.
--
-- ⚠️ Generated by scripts/generate-deactivation-guards.mjs from
-- `pg_get_functiondef`. Regenerate rather than hand-editing.

-- ── The bodies, rewritten from the catalogue ──────────────────────────────
-- my_notifications: auth.uid() -> active_uid(), 1 occurrence(s).
CREATE OR REPLACE FUNCTION public.my_notifications(p_days integer DEFAULT 30)
 RETURNS TABLE(id uuid, kind text, title text, body text, link text, read_at timestamp with time zone, created_at timestamp with time zone, entity_type text, entity_id uuid, target_live boolean)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select
    n.id, n.kind, n.title, n.body, n.link, n.read_at, n.created_at,
    n.entity_type, n.entity_id,
    case
      when n.entity_id is null then true          -- a static link cannot dangle
      when n.entity_type = 'ticket'             then exists (select 1 from tickets t             where t.id = n.entity_id)
      when n.entity_type = 'payment'            then exists (select 1 from payments p            where p.id = n.entity_id)
      when n.entity_type = 'asset'              then exists (select 1 from assets a               where a.id = n.entity_id)
      when n.entity_type = 'property'           then exists (select 1 from properties r           where r.id = n.entity_id)
      when n.entity_type = 'lease'              then exists (select 1 from leases l                where l.id = n.entity_id)
      when n.entity_type = 'tenant_application' then exists (select 1 from tenant_applications a   where a.id = n.entity_id and a.purged_at is null)
      else true
    end
  from user_notifications n
  where n.user_id = active_uid()
    and (n.read_at is null or n.created_at >= now() - make_interval(days => greatest(p_days, 1)))
  order by n.read_at nulls first, n.created_at desc;
$function$
;

-- accept_tenancy_offer: guard injected after the opening begin.
CREATE OR REPLACE FUNCTION public.accept_tenancy_offer(p_token_hash text, p_invite_token_hash text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  o tenancy_offers%rowtype;
  a tenant_applications%rowtype;
  v_invite_id uuid;
  v_unit text;
begin
  -- Deactivation guard. Null-safe by construction: current_user_is_active()
  -- returns a boolean from exists(), never NULL, and the auth.uid() test keeps
  -- the service role (scheduled jobs, webhooks) passing straight through.
  if auth.uid() is not null and not current_user_is_active() then
    raise exception 'this account has been deactivated';
  end if;

  select * into o from tenancy_offers where accept_token_hash = p_token_hash for update;
  if o.id is null then
    raise exception 'this offer link is no longer valid';
  end if;
  if o.status <> 'issued' then
    raise exception 'this offer has already been %', o.status;
  end if;
  if o.expires_on < current_date then
    raise exception 'this offer lapsed on %', to_char(o.expires_on, 'DD Mon YYYY');
  end if;
  if coalesce(p_invite_token_hash, '') = '' then
    raise exception 'accepting needs an invitation token';
  end if;

  select * into a from tenant_applications where id = o.application_id;

  -- ⚠️ `issued_by`, not `auth.uid()`. There is no session here by definition —
  -- the person accepting has no account, which is the whole reason acceptance
  -- creates one. Stamping null would leave the invitation with no author, which
  -- is the fault 0142 had to go back and fix on remittances.
  insert into invitations (org_id, email, role, full_name, unit_id, token_hash, invited_by, expires_at)
  values (o.org_id, a.applicant_email, 'tenant', a.applicant_name, o.unit_id,
          p_invite_token_hash, o.issued_by, now() + interval '14 days')
  returning id into v_invite_id;

  update tenancy_offers
     set status = 'accepted', responded_at = now()
   where id = o.id;

  select label into v_unit from units where id = o.unit_id;

  perform notify_application_desk(
    a.id,
    'A tenancy offer was accepted',
    a.applicant_name || ' accepted the offer on ' || coalesce(v_unit, 'their unit') ||
    '. Record the tenancy to start billing it.'
  );

  return jsonb_build_object(
    'invitation_id', v_invite_id,
    'org_id', o.org_id,
    'application_id', a.id,
    'email', a.applicant_email,
    'name', a.applicant_name
  );
end;
$function$
;

-- operator_set_approval_chain: guard injected after the opening begin.
CREATE OR REPLACE FUNCTION public.operator_set_approval_chain(p_org_id uuid, p_shape text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_before text;
begin
  -- Deactivation guard. Null-safe by construction: current_user_is_active()
  -- returns a boolean from exists(), never NULL, and the auth.uid() test keeps
  -- the service role (scheduled jobs, webhooks) passing straight through.
  if auth.uid() is not null and not current_user_is_active() then
    raise exception 'this account has been deactivated';
  end if;

  if not caller_is_operator_admin() then
    raise exception 'only an OE Group operator administrator may set an organisation''s approval chain';
  end if;

  if p_shape is not null and p_shape not in ('standard', 'oea', 'single_stage') then
    raise exception 'unknown approval chain shape: %', p_shape;
  end if;

  select approval_chain_shape into v_before from orgs where id = p_org_id;
  if not found then
    raise exception 'no such organisation';
  end if;

  update orgs set approval_chain_shape = p_shape where id = p_org_id;

  -- Written explicitly rather than left to the generic table trigger: this is a
  -- change to a money control, and the audit row should say so in words an
  -- auditor reads, not as a column diff on an org record.
  insert into audit_log (org_id, actor_id, action, entity_type, entity_id,
                         before_state, after_state)
  values (
    p_org_id, auth.uid(), 'payment_chain.shape_changed', 'orgs', p_org_id,
    jsonb_build_object('approval_chain_shape', v_before),
    jsonb_build_object('approval_chain_shape', p_shape)
  );
end;
$function$
;

-- operator_set_approval_tiers: guard injected after the opening begin.
CREATE OR REPLACE FUNCTION public.operator_set_approval_tiers(p_org_id uuid, p_enabled boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_before boolean;
begin
  -- Deactivation guard. Null-safe by construction: current_user_is_active()
  -- returns a boolean from exists(), never NULL, and the auth.uid() test keeps
  -- the service role (scheduled jobs, webhooks) passing straight through.
  if auth.uid() is not null and not current_user_is_active() then
    raise exception 'this account has been deactivated';
  end if;

  if not caller_is_operator_admin() then
    raise exception 'only an OE Group operator administrator may switch approval tiers on or off';
  end if;

  select approval_tiers_enabled into v_before from orgs where id = p_org_id;
  if not found then
    raise exception 'no such organisation';
  end if;

  update orgs set approval_tiers_enabled = coalesce(p_enabled, false) where id = p_org_id;

  insert into audit_log (org_id, actor_id, action, entity_type, entity_id,
                         before_state, after_state)
  values (
    p_org_id, auth.uid(), 'payment_chain.tiers_changed', 'orgs', p_org_id,
    jsonb_build_object('approval_tiers_enabled', v_before),
    jsonb_build_object('approval_tiers_enabled', coalesce(p_enabled, false))
  );
end;
$function$
;

-- ── The privileges each of them held before this migration ───────────────
--
-- Read from the catalogue and re-stated, because `create or replace` is where
-- a closed door quietly reopens (0204, 0209, 0210, 0264).
revoke all on function my_notifications(p_days integer) from public, anon, authenticated;
grant execute on function my_notifications(p_days integer) to authenticated, service_role;
revoke all on function accept_tenancy_offer(p_token_hash text, p_invite_token_hash text) from public, anon, authenticated;
grant execute on function accept_tenancy_offer(p_token_hash text, p_invite_token_hash text) to service_role;
revoke all on function operator_set_approval_chain(p_org_id uuid, p_shape text) from public, anon, authenticated;
grant execute on function operator_set_approval_chain(p_org_id uuid, p_shape text) to authenticated, service_role;
revoke all on function operator_set_approval_tiers(p_org_id uuid, p_enabled boolean) from public, anon, authenticated;
grant execute on function operator_set_approval_tiers(p_org_id uuid, p_enabled boolean) to authenticated, service_role;

comment on function resolve_chat_sender is
  'Who is writing to us on WhatsApp or Telegram, by their phone number. A deactivated account resolves to nobody (0195) - this path runs service-role from the webhook, so RLS and the 0194 resolvers never see it, and without the clause here the primary intake channel stayed open to someone the organisation had removed.';

-- ── The notification feed ─────────────────────────────────────────────────
-- `user_notifications_select` was `using (user_id = auth.uid())`: no org gate
-- and no deactivation. It is also what `my_notifications` reads through — that
-- one being the single non-DEFINER function in the set — so the policy fixes
-- both.
drop policy if exists user_notifications_select on user_notifications;
create policy user_notifications_select on user_notifications for select
  using (user_id = active_uid());

comment on policy user_notifications_select on user_notifications is
  'Your own notifications, for as long as the account is live (0195).';

-- ── Prove the RULE, not the list ──────────────────────────────────────────
-- 0194's check named four functions and asserted a substring appeared in each.
-- It would have passed unchanged on the day every gap above was open, which is
-- exactly what its own header argues against: it proved the clause was PRESENT,
-- never that anything REFUSED.
--
-- This asks the catalogue instead. Every function in `public` that reaches
-- auth.uid() must either resolve identity through a deactivation-aware path, or
-- be named below with the reason it cannot. A function added later that does
-- neither fails the migration that introduces it.
do $$
declare
  v_bad text[] := '{}';
  r record;
begin
  for r in
    select p.proname, pg_get_functiondef(p.oid) as def,
           pg_get_function_result(p.oid) as ret
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f'
       and pg_get_functiondef(p.oid) like '%auth.uid()%'
  loop
    -- A trigger cannot refuse a caller it was not called about: it fires on a
    -- row, and the write that reached it has already passed RLS. Guarding
    -- log_audit() would block the write it exists to record.
    continue when r.ret = 'trigger';

    continue when r.proname = any (array[
      -- creates the users row - a guard reading that row would refuse every new joiner
      'accept_invitation',
      -- not SECURITY DEFINER - runs under RLS as the caller, which already fails closed
      'reject_payment'
    ]);

    -- A function that refuses EVERY signed-in caller outright is not a gap: it
    -- cannot be reached by a deactivated account because it cannot be reached
    -- by any account. Asking it to also read `deactivated_at` would be asking
    -- it to look up a row it has already refused to serve.
    -- `escalate_stale_unassigned_requests` (0212) is the first of these, and it
    -- is recognised as a RULE rather than named, so the next one needs no edit
    -- here. verify-deactivation.mjs section E carries the same rule — the two
    -- must agree, and a disagreement is worth the failure it causes.
    continue when r.def ~* 'if\s+auth\.uid\(\)\s+is\s+not\s+null\s+then\s+raise';

    if r.def !~ '(deactivated_at\s+is\s+null|active_uid\(\)|current_user_is_active\(\)|current_user_org_id\(\)|current_user_role\(\)|current_user_property_ids\(\)|current_user_vendor_ids\(\))'
    then
      v_bad := v_bad || r.proname;
    end if;
  end loop;

  if array_length(v_bad, 1) > 0 then
    raise exception
      'These functions reach auth.uid() with no deactivation-aware path and are not declared exceptions: %',
      array_to_string(v_bad, ', ');
  end if;
end;
$$;
